
export const GET_HOUSE_STATS: "GET_HOUSE_STATS" = "GET_HOUSE_STATS";
export const GET_RECOMMENDATION_CARDS: "GET_RECOMMENDATION_CARDS" = "GET_RECOMMENDATION_CARDS";
export const GET_REVIEW_CARDS: "GET_REVIEW_CARDS" = "GET_REVIEW_CARDS";
export const GET_TIPS_AND_TRICKS_CARDS: "GET_TIPS_AND_TRICKS_CARDS" = "GET_TIPS_AND_TRICKS_CARDS";